#!/usr/bash

#set args -b 8 -e 1024M -f 2 -t 1 -g 4
set breakpoint pending on
set trace-commands on
set logging on
#set can-use-hw-watchpoints 0
set pagination off



#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:52
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:76
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:77
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:85
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:87
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:89
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:92




#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:767
break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:403
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:92
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:92
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:92
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:92


ignore 1 74

#break src/common.cu:330


#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/common_kernel.h:245
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/common_kernel.h:274


run

- 


-
