#!/usr/bash

#set args -b 8 -e 1024M -f 2 -t 1 -g 4
set breakpoint pending on
set trace-commands on
set logging on
#set can-use-hw-watchpoints 0
set pagination off



#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:52
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:76
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:77
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:85
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:87
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:89
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/all_reduce.h:92



#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/all_reduce.cu:62
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:485
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:499
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:502
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:503
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:506
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:509
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:512
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:406
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:413
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:419
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:439
#break /nfs/scistore08/alistgrp/hramezan/nccl-tests/src/common.cu:441



#break /nfs/scistore08/alistgrp/hramezan/nccl/src/group.cc:247



#break /nfs/scistore08/alistgrp/hramezan/nccl/src/init.cc:245
break /nfs/scistore08/alistgrp/hramezan/nccl/src/proxy.cc:153
break /nfs/scistore08/alistgrp/hramezan/nccl/src/group.cc:123
break /nfs/scistore08/alistgrp/hramezan/nccl/src/group.cc:231
break /nfs/scistore08/alistgrp/hramezan/nccl/src/enqueue.cc:368
break /nfs/scistore08/alistgrp/hramezan/nccl/src/enqueue.cc:532


#break src/common.cu:330


#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/common_kernel.h:245
#break /nfs/scistore08/alistgrp/hramezan/nccl/src/collectives/device/common_kernel.h:274


run

- 


-
